version: '3.7'
volumes:
  yb1-data:
  yb1-master:
  yb2-data:
  yb2-master:
  yb3-data:
  yb3-master:
  yb4-data:
  yb4-master:

services:
  yb1:
    build:
      context: ./
      dockerfile: manual.Dockerfile
    container_name: yb1
    hostname: yb1
    
    ports:
      - "7001:7000"
      - "9001:9000"
      - "5431:5433"
    volumes:
      - yb1-data:/mnt/disk1
      - yb1-master:/mnt/disk0


  yb2:
    build:
      context: ./
      dockerfile: manual.Dockerfile
    container_name: yb2
    hostname: yb2
    ports:
      - "7002:7000"
      - "9002:9000"
      - "5432:5433"
    volumes:
      - yb2-data:/mnt/disk1
      - yb2-master:/mnt/disk0



  yb3:
    build:
      context: ./
      dockerfile: manual.Dockerfile
    container_name: yb3
    hostname: yb3
    ports:
      - "7003:7000"
      - "9003:9000"
      - "5433:5433"
    volumes:
      - yb3-data:/mnt/disk1
      - yb3-master:/mnt/disk0
  yb4:
    build:
      context: ./
      dockerfile: manual.Dockerfile
    container_name: yb4
    hostname: yb4
    ports:
      - "7004:7000"
      - "9004:9000"
      - "5434:5433"
    volumes:
      - yb4-data:/mnt/disk1
      - yb4-master:/mnt/disk0

